
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 16 10:17:18 EDT 2015
//----------------------------------------------------

package accrue.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int REMOVE_GUARDED_BY_PC = 19;
  public static final int STRING_LITERAL = 37;
  public static final int IS_EMPTY = 26;
  public static final int EQUALS = 3;
  public static final int FOR_PROCEDURE = 16;
  public static final int FORWARD_SLICE = 8;
  public static final int FOR_EXPRESSION = 15;
  public static final int AND = 5;
  public static final int REMOVE_EDGES = 12;
  public static final int NODE_BY_ID = 27;
  public static final int RPAR = 33;
  public static final int SELECT_NODES = 13;
  public static final int FIND_PC_NODES = 20;
  public static final int IN = 4;
  public static final int OR = 6;
  public static final int COMMA = 31;
  public static final int BACKWARD_SLICE = 9;
  public static final int SHORTEST_PATH = 10;
  public static final int DOT = 34;
  public static final int EOF = 0;
  public static final int REMOVE_GUARDED_BY = 17;
  public static final int NODE_TYPE = 36;
  public static final int error = 1;
  public static final int BOOL_NOT = 21;
  public static final int BOOL_AND = 22;
  public static final int LBRACK = 24;
  public static final int REMOVE_NODES = 11;
  public static final int REMOVE_GUARDED_BY_BOOL = 18;
  public static final int POSITION = 28;
  public static final int NODES_IN_CONTEXT = 29;
  public static final int RBRACK = 25;
  public static final int PDG = 7;
  public static final int LET = 2;
  public static final int EDGE_TYPE = 35;
  public static final int LPAR = 32;
  public static final int BOOL_OR = 23;
  public static final int RESTRICT = 30;
  public static final int SELECT_EDGES = 14;
  public static final int INT_LITERAL = 38;
  public static final int IDENTIFIER = 39;
}

